# config/biomass.yaml

years:
  - 2024
  - 2025

affiliation_source_column: "Image Name (from PlantMap3D app)"

affiliation_map:
  AL-Wolfe: AL01
  NY-Jannink: NY02
  AL-Oyebode: AL02
  IA-Corteva: IA01
  IL-Arbelaez: IL02
  ND-Berti: ND02
  FL-Rios: FL01

rename_map:
  Timing: timing
  Plot ID: plot_id
  Dry Wt (g): dry_weight_g

drop_zero_weight: false